INSERT IGNORE INTO m_permission VALUES (null,'billing', 'CREATE_PROVISIONINGPLANMAPPING', 'PROVISIONINGPLANMAPPING', 'CREATE', 0);
INSERT IGNORE INTO m_permission VALUES (null,'billing', 'UPDATE_PROVISIONINGPLANMAPPING', 'PROVISIONINGPLANMAPPING', 'UPDATE', 0);
INSERT IGNORE INTO m_permission VALUES (null,'billing', 'DELETE_PROVISIONINGPLANMAPPING', 'PROVISIONINGPLANMAPPING', 'DELETE', 0);
INSERT IGNORE INTO  m_permission VALUES(null,'billing', 'GENERATENEWPASSWORD_SELFCARE', 'SELFCARE', 'GENERATENEWPASSWORD', '0');
INSERT IGNORE INTO  m_permission VALUES(null,'billing', 'UPDATE_SELFCARE', 'SELFCARE', 'UPDATE', '0');





